### ISSUE TITLE
Found argument 'invoice' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by josediegorobles** [RGB-WG/rgb-node#169]
I'm trying to make and invoice according to README and I get this at this step:

rgb1-cli fungible invoice <contract_id> 500 <txid>:<txout>
error: Found argument 'invoice' which wasn't expected, or isn't valid in this context

If you tried to supply `invoice` as a PATTERN use `-- invoice`

USAGE:
    rgb-cli fungible [FLAGS] <SUBCOMMAND>

It's the same if I use rgb1-cli -vvvv fungible invoice etc.

**Comment by dr-orlovsky** [comment]
Which version are you used, produced from `git clone` from master + `cargo build` – or one after `cargo install`?

**Comment by josediegorobles** [comment]
Oh, I see, I produced it by cargo install. It can be closed.

**Comment by josediegorobles** [comment]
So the problem is now that with cargo build it only says:

Finished release [optimized] target(s) in 0.25s

and then, with:

target/release/rgbd --data-dir ~/.rgb --bin-dir target/release -vvvv --contract fungible

bash: target/release/rgbd: No such file or directory

**Comment by josediegorobles** [comment]
Ok, I did a build with:

cargo build--locked --features all

It worked...

But I have the same problem again:

Found argument 'invoice' which wasn't expected, or isn't valid in this context
