### ISSUE TITLE
Issue installing prerequisites for RGB-node

### ISSUE THREAD

**Issue by MaxSikorski** [RGB-WG/rgb-node#171]
[RGB-node_Eden1_on_Pi_Logs.txt](https://github.com/rgb-org/rgb-node/files/6393043/RGB-node_Eden1_on_Pi_Logs.txt)

**Comment by MaxSikorski** [comment]
@Supertestnet has helped me with this process. I will tag him as well

**Comment by dr-orlovsky** [comment]
I'm afraid this is a pure docker+raspberry issue and there is not much we can do with it here
