### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by joepeak** [RGB-WG/rgb-node#176]
Hello,some erros appear,when i compile,Can someone help me? Errors info below:

![image](https://user-images.githubusercontent.com/4530403/147467577-2a51ceab-15b8-456f-938d-a3213e31146b.png)

My environment is as follows:

mac:mac os 11.6
rust:rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by dr-orlovsky** [comment]
Sorry, the current master is outdated pending update with Taproot in rust-bitcoin, which is going to be released in the next days. If you really need to build the node you can use `v0.4.0` tag
