### ISSUE TITLE
Proposal for proof-of-payment protocol

### ISSUE THREAD

**Issue by fedsten** [RGB-WG/rgb-node#179]
**Motivation**
When you perform a payment, it is important to be able to prove to third parties that the payment was indeed finalized correctly. This is relevant for example in case of disputes between parties or when dealing with service providers such as centralised exchanges. With normal Bitcoin transactions, you always have the blockchain as a source of truth to testify that a specific transaction did indeed occur as agreed between the parties and was finalised. However, in RGB there is the consignment data which is transferred off-chain, with no on-chain record to prove that the consignment was truly delivered to the payee.

**Proposal**
To address the issue, an interactive protocol is needed, with the requirement for the payee to provide a signed receipt of received consignment before the payer proceeds to perform the Bitcoin transaction to close the single-use-seal. Specifically, the protocol should include the following steps:

1. The payee sends an invoice to the payer.
2. The payer sends the consignment data to the payee.
3. The payee validates the consignment.
4. The payee sends a signed receipt to the payer acknowledging that the correct consignment was received and validated.
5. The payer closes the on-chain single-use-seal, and commits the consignment in the output of the Bitcoin transaction.
6. The payee monitors the blockchain and as soon as the Bitcoin transaction receives a sufficient number of confirmations, the payment is considered finalised. In case the RGB assets are being moved on a Lightning Network payment channel, the payment will be considered finalised when the channel is updated.

![Screenshot from 2022-03-23 13-48-14](https://user-images.githubusercontent.com/31323835/159702755-eea9f47e-dbf1-4aae-b563-f30223d267f6.png)

**Comment by dr-orlovsky** [comment]
Thank you! I think this will be nice to have as a standard. Can you please re-post the proposal into https://github.com/LNP-BP/LNPBPs/discussions/categories/standard-proposals?

**Comment by dr-orlovsky** [comment]
Closing due to movement into https://github.com/LNP-BP/LNPBPs/discussions/122
