### ISSUE TITLE
no 'MesgPush' in the root

### ISSUE THREAD

**Issue by Goosie** [RGB-WG/rgb-node#186]
Trying to follow the steps in the demo from last week 28 June 2022 ;
And after solving the issue to get the store_deamon installed (ON UBUNTU) by using the command:
cargo install store_daemon --all-features --version 0.8.0-rc.1 I run into a next error when installing rgb-node. I install this out of the source code out of the repos directory:
git clone https://github.com/LNP-BP/rgb-node.git
cargo install --all-features --path .
Gives the error:
error[E0432]: unresolved import `storm_ext::MesgPush`
  --> src/rgbd/service.rs:32:37
   |
32 | use storm_ext::{ExtMsg as StormMsg, MesgPush};
   |                                     ^^^^^^^^ no `MesgPush` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rgb_node` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rgb_node v0.8.0-rc.2 (/home/perry/repos/rgb-node)`, intermediate artifacts can be found at `/home/perry/repos/rgb-node/target`

**Comment by Goosie** [comment]
When I try it with the command: cargo install rgb_node --all-features --version 0.8.0-beta.2
I get:
   Compiling psbt v0.7.1
error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:174:33
    |
171 | ...                   DeriveDescriptor::<XOnlyPublicKey>::derive_descriptor(
    |                       ----------------------------------------------------- required by a bound introduced by this call
...
174 | ...                       &input.terminal,
    |                           ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `derive_descriptor`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/derive.rs:117:19
    |
117 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `derive_descriptor`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:188:33
    |
185 | ...                   DeriveDescriptor::<bitcoin::PublicKey>::derive_descriptor(
    |                       --------------------------------------------------------- required by a bound introduced by this call
...
188 | ...                       &input.terminal,
    |                           ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `derive_descriptor`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/derive.rs:117:19
    |
117 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `derive_descriptor`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:209:58
    |
209 |                     match account.bip32_derivation(secp, &input.terminal) {
    |                                   ----------------       ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |                                   |
    |                                   required by a bound introduced by this call
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `TrackingAccount::bip32_derivation`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/account.rs:211:19
    |
211 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `TrackingAccount::bip32_derivation`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:257:57
    |
257 | ...                   .bip32_derivation(secp, &input.terminal)
    |                        ----------------       ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `TrackingAccount::bip32_derivation`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/account.rs:211:19
    |
211 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `TrackingAccount::bip32_derivation`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:282:53
    |
282 | ...                   .bip32_derivation(secp, &input.terminal)
    |                        ----------------       ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `TrackingAccount::bip32_derivation`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/account.rs:211:19
    |
211 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `TrackingAccount::bip32_derivation`

   Compiling psbt v0.8.4
error[E0599]: no method named `as_u32` found for struct `LockTime` in the current scope
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:398:34
    |
398 |             lock_time: lock_time.as_u32(),
    |                                  ^^^^^^ method not found in `LockTime`

error[E0599]: no method named `as_u32` found for struct `SeqNo` in the current scope
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:403:44
    |
403 |                     sequence: input.seq_no.as_u32(),
    |                                            ^^^^^^ method not found in `SeqNo`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `psbt` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rgb_node v0.8.0-beta.2`, intermediate artifacts can be found at `/tmp/cargo-install6Hx2Lg`
perry@Desktop:~/.demo$ cargo install rgb_node --all-features --version 0.8.0-beta.2

**Comment by grunch** [comment]
What rust version are you runing? did you installed the dependencies?
```
sudo apt install -y build-essential cmake libpq-dev libsqlite3-dev libssl-dev libzmq3-dev pkg-config
```

**Comment by Goosie** [comment]
Rust version: nightly by doing rustup default nightly and rustup update rustc --version gives: rustc 1.62.0 (a8314ef7d 2022-06-27)

I run this command again: sudo apt install -y build-essential cmake libpq-dev libsqlite3-dev libssl-dev libzmq3-dev pkg-config

Than after running the command : cargo install rgb_node --all-features --version 0.8.0-beta.2

I still get the following errors:
error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:174:33
    |
171 | ...                   DeriveDescriptor::<XOnlyPublicKey>::derive_descriptor(
    |                       ----------------------------------------------------- required by a bound introduced by this call
...
174 | ...                       &input.terminal,
    |                           ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `derive_descriptor`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/derive.rs:117:19
    |
117 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `derive_descriptor`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:188:33
    |
185 | ...                   DeriveDescriptor::<bitcoin::PublicKey>::derive_descriptor(
    |                       --------------------------------------------------------- required by a bound introduced by this call
...
188 | ...                       &input.terminal,
    |                           ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `derive_descriptor`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/derive.rs:117:19
    |
117 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `derive_descriptor`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:209:58
    |
209 |                     match account.bip32_derivation(secp, &input.terminal) {
    |                                   ----------------       ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |                                   |
    |                                   required by a bound introduced by this call
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `TrackingAccount::bip32_derivation`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/account.rs:211:19
    |
211 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `TrackingAccount::bip32_derivation`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:257:57
    |
257 | ...                   .bip32_derivation(secp, &input.terminal)
    |                        ----------------       ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `TrackingAccount::bip32_derivation`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/account.rs:211:19
    |
211 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `TrackingAccount::bip32_derivation`

error[E0277]: the trait bound `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>: AsRef<[UnhardenedIndex]>` is not satisfied
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:282:53
    |
282 | ...                   .bip32_derivation(secp, &input.terminal)
    |                        ----------------       ^^^^^^^^^^^^^^^ the trait `AsRef<[UnhardenedIndex]>` is not implemented for `bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the trait `AsRef<[Segment]>` is implemented for `bitcoin_hd::path::DerivationSubpath<Segment>`
    = note: required because of the requirements on the impl of `AsRef<[UnhardenedIndex]>` for `&bitcoin_hd::path::DerivationSubpath<bitcoin_hd::indexes::UnhardenedIndex>`
note: required by a bound in `TrackingAccount::bip32_derivation`
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hd-0.7.1/src/account.rs:211:19
    |
211 |         pat: impl AsRef<[UnhardenedIndex]>,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `TrackingAccount::bip32_derivation`

error[E0599]: no method named `as_u32` found for struct `LockTime` in the current scope
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:398:34
    |
398 |             lock_time: lock_time.as_u32(),
    |                                  ^^^^^^ method not found in `LockTime`

error[E0599]: no method named `as_u32` found for struct `SeqNo` in the current scope
   --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/psbt-0.7.1/src/construct/mod.rs:403:44
    |
403 |                     sequence: input.seq_no.as_u32(),
    |                                            ^^^^^^ method not found in `SeqNo`

   Compiling psbt v0.8.4
Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `psbt` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rgb_node v0.8.0-beta.2`, intermediate artifacts can be found at `/tmp/cargo-installuJPM4s`

**Comment by Goosie** [comment]
I removed the rgb-node directory and load the source again from github and tried to compile again I get only the error:

error[E0432]: unresolved import `storm_ext::MesgPush`
  --> src/rgbd/service.rs:32:37
   |
32 | use storm_ext::{ExtMsg as StormMsg, MesgPush};
   |                                     ^^^^^^^^ no `MesgPush` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rgb_node` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rgb_node v0.8.0-rc.2 (/home/perry/repos/rgb-node)`, intermediate artifacts can be found at `/home/perry/repos/rgb-node/target`

**Comment by grunch** [comment]
go to master and build instead

`cargo build --all-features --bins`

if it compiles correctly the binary files will be on `target/debug`

**Comment by Goosie** [comment]
That seems to work. I only got a warning:
warning: unused variable: `message`
   --> src/rgbd/service.rs:155:39
    |
155 |             StormMsg::Post(MesgPush { message, container }) => {}
    |                                       ^^^^^^^ help: try ignoring the field: `message: _`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `container`
   --> src/rgbd/service.rs:155:48
    |
155 |             StormMsg::Post(MesgPush { message, container }) => {}
    |                                                ^^^^^^^^^ help: try ignoring the field: `container: _`

warning: `rgb_node` (lib) generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 2m 18s

**Comment by grunch** [comment]
yeah I got those warnings too, don't worry much about it, rgb node is WIP

**Comment by Goosie** [comment]
Than we can close this, thanks for the quick support.
