### ISSUE TITLE
Release latest rgb_node 0.8.0 to crates.io

### ISSUE THREAD

**Issue by cryptoquick** [RGB-WG/rgb-node#199]
See: https://crates.io/crates/rgb_node/versions

**Comment by dr-orlovsky** [comment]
Pending #204

**Comment by zoedberg** [comment]
Before of releasing rgb-node we need to release rgb-core since https://github.com/RGB-WG/rgb-core/pull/110 has been merged and contains an important fix. Moreover I think that after releasing rgb-core we will need to release also rgb-std first.

**Comment by dr-orlovsky** [comment]
Yes. And we need to fix BP Core with the Tapret commitments

**Comment by cryptoquick** [comment]
LFG! :rocket:
