### ISSUE TITLE
Unable to install rgb-node

### ISSUE THREAD

**Issue by afeezaziz** [RGB-WG/rgb-node#255]
I am running MacOS. When installing by using this `cargo install --all-features --bins --path .`, this is the error that I face:
<img width="850" alt="Screenshot 2023-10-07 at 2 46 55 PM" src="https://github.com/RGB-WG/rgb-node/assets/677026/7d8bdcd8-bdb2-41ad-bc3b-8a98bbdfb1aa">

Then I tried with Docker, by using this command: `docker build -t rgb-node .`
<img width="843" alt="Screenshot 2023-10-07 at 2 45 21 PM" src="https://github.com/RGB-WG/rgb-node/assets/677026/758f85d9-b045-4e5d-a543-e33a4d4659e6">

Please let me know how can I go through installing the rgb-node. I was able to install rgb-cli though.

**Comment by afeezaziz** [comment]
Second question, do you need rgb-node to issue contract, or do some transfer for RGB20?

Or is it just if you would like to see the RGB20 on the mainnet?

**Comment by dr-orlovsky** [comment]
You do not need RGB node to get RGB working.

The current RGB node is outdated and will be updated later - please do not use it to work with the modern RGB version.

See the instructions on how to use RGB with the command-line tool from https://github.com/RGB-WG/rgb on https://rgb.tech/power-user/
