### ISSUE TITLE
problem when install RGB node 

### ISSUE THREAD

**Issue by yansc153** [RGB-WG/rgb-node#257]
I was trying to install RGB node with this command "cargo install --path . --all-fesutres ." but it keeps saying that 

error[E0275]: overflow evaluating the requirement `D: std::io::Read`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "512"]` attribute to your crate (`bitcoin_scripts`)
  = note: required for `&mut D` to implement `std::io::Read`
  = note: 256 redundant requirements hidden
  = note: required for `&mut &mut &mut &mut &mut &mut &mut &mut &mut ...` to implement `std::io::Read`
  = note: the full type name has been written to '/Users/oxjames/rgb/demo/rgb-node/target/release/deps/bitcoin_scripts-2f1138789d576eaa.long-type-1292279127761535772.txt'

For more information about this error, try `rustc --explain E0275`.
error: could not compile `bitcoin_scripts` (lib) due to previous error
error: failed to compile `rgb_node v0.9.2 (/Users/oxjames/rgb/demo/rgb-node)`, intermediate artifacts can be found at `/Users/oxjames/rgb/demo/rgb-node/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

any help?

**Comment by dr-orlovsky** [comment]
Please see https://github.com/RGB-WG/rgb-node/issues/255#issuecomment-1751674159
