### ISSUE TITLE
Check network correspondence when issuing assets

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-node#65]
https://github.com/LNP-BP/rgb-node/blob/4e9e632c85ae808e81044b4147076879f9701ace/src/i9n/fungible.rs#L55

**Comment by rajarshimaitra** [comment]
It seems outdated?

https://github.com/rgb-org/rgb-node/blob/9e686d538b79198d28e1f81b989323dd7ea15646/src/i9n/fungible.rs#L50-L80

**Comment by dr-orlovsky** [comment]
It still has to be implemented, but on a higher level
